### PR TITLE
Update deprecated method - Scenario.embed() to Scenario.attach() "Fixes #486"

### LINKED ISSUE #486: documentation for attaching infos to scenario in cucumber-jvm
The documentation for attaching text/screenshot to the scenario is a bit outdated

https://cucumber.io/docs/guides/browser-automation/?sbsearch=attach#browser-automation-tools-for-jvm
In Cucumber 5.7.0 the emed is deprecated, and if I got it right in v6 it is removed and replaced with attach.

### PR DESCRIPTION
**Pull request by josepj**
[5.7.0](https://github.com/cucumber/cucumber-jvm/blob/main/CHANGELOG.md#570-2020-05-01) (2020-05-01)
Added
[Java] Scenario.log(String) & Scenario.attach(byte[], String, String) (#1893 Tim te Beek)
Deprecated
[Java] Scenario.write(String) & Scenario.embed(byte[], String, String) (#1893 Tim te Beek)

### CODE REVIEW

**Review by luke-hill — COMMENTED** [review]
Could you scan the doc for all instances of this in all languages. As it makes sense to fix them all up now (They're all updated).

**Comment by josepj** [comment]
@luke-hill, thanks for looking into this. I looked through the docs and could find only one other instance of embed, for Ruby. I have updated the code, but I am not familiar with Ruby. So please review the change.

[4.0.0.rc.4](https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#400rc4)
Added
Methods log and attach can be used in step definitions to attach text or images
Deprecated
embed in step definitions in favor of attach [(cucumber#897)](https://github.com/cucumber/cucumber/issues/897)

**Review by mlvandijk — COMMENTED** [review]
LGTM but I have not scanned the project for other instances.

**Comment by mlvandijk** [comment]
Does this fix #486? If so, please make sure that gets closed on merge (iirc you can do so automatically by adding "Fixes #486" to the name of the PR)

**Review by luke-hill — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @josepj,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
