### PR TITLE
Add a fun GIF to the otherwise empty 404 page

### PR DESCRIPTION
**Pull request by mikegfisher**
In case you want a fun 404 page

### CODE REVIEW

**Comment by mikegfisher** [comment]
RE: #148

**Comment by mlvandijk** [comment]
Hello @mikegfisher , thanks for your PR's. 
It's a funny gif (https://media.giphy.com/media/5q9uPPzOPsQAE/giphy.gif) and I'd love to see how it looks on the page. Unfortunately, the build fails with:
```
- public/404.html
10:03:58 AM:   *  image https://media.giphy.com/media/5q9uPPzOPsQAE/giphy.gif does not have an alt attribute (line 29)
10:03:58 AM: /opt/build/cache/bundle/ruby/2.4.0/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:167:in `print_failed_tests': HTML-Proofer found 1 failure! (RuntimeError)
```
Would you be able to add an alt attribute?

Also, @robzenn92 had some ideas regarding the rest of the page, as you can see in #148 - If you'd like to collaborate, please join us in Slack channel #docs. :)

**Comment by mikegfisher** [comment]
Yep - I took out the {{main}} block because nothing was rendering, but I'm not really familiar with GitHub pages/ Hugo.

**Review by mlvandijk — CHANGES_REQUESTED** [review]
Well, it's better than a blank page so I'm tempted to merge (for now).
On the other hand, I'd like to be nice about not being able to find a page, and at least point them back to the docs landing page. Think you could add that @mikegfisher?

**Comment by mlvandijk** [comment]
Any thoughts on this @aslakhellesoy @plaindocs ?

**Comment by mikegfisher** [comment]
Sure, done. I mean - hopefully nobody sees it anyways 😅but something (especially a funny GIF) is better than nothing.

**Comment by mlvandijk** [comment]
Agreed! Thanks @mikegfisher! (@robzenn92 feel free to improve upon this further!)

**Pull request merged**
