### PR TITLE
Fix number formatting in css

### PR DESCRIPTION
**Pull request by mlvandijk**
This seems to do the trick.
See preview: https://deploy-preview-43--cucumber.netlify.com/cucumber/browser-automation/

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
The preview you showed looked very regular.

Good change!

**Comment by plaindocs** [comment]
Thanks for fixing @mlvandijk ! 

`prism.js` is usually generated, so perhaps it was a rogue plugin for that.

http://prismjs.com/plugins/line-highlight/ kinda thing.

**Comment by mlvandijk** [comment]
@plaindocs If it's generated then it might be generated again? in which case this fix will not hold... Will figure that out should it become relevant :)

**Comment by plaindocs** [comment]
Exactly, that is why I left this breadcrumb. ;-)

Prism is the JS syntax highlighting library, and afaik you select the languages+plugins you want and download a JS blob.

**Pull request merged**
