### PR TITLE
Update versions.yaml

### PR DESCRIPTION
**Pull request by aurelien-reeves**

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
@mpkorstanje should we update junit to 5?

**Comment by mpkorstanje** [comment]
> @mpkorstanje should we update junit to 5?

Not until Cucumber v7 and Junit 5.8 is GA.

**Comment by aurelien-reeves** [comment]
Ok, thanks

So, can we merge?

**Comment by mpkorstanje** [comment]
Sure. 

I haven't been keeping up with the docs project much. But it's not a major change so I expect everything will still be accurate.

**Pull request merged**
