### PR TITLE
Update step-definitions.md

### PR DESCRIPTION
**Pull request by AReyes-cl**
Fix java regexp notation in expression

### CODE REVIEW

**Review by olleolleolle — COMMENTED** [review]
If you read the paragraph after the code samples, they seem to be about Cucumber Expressions, which are surrounded by curly braces. The sentence about capture group handling explains how to use that with the {int} expression. 

It seems to me that these code samples should be Cucumber Expressions all.

**Comment by luke-hill** [comment]
Yeh the four capture blocks have 2 as regexp and 2 as cukeexp.

Might I suggest a change that adds both options to all four blocks?

**Comment by mlvandijk** [comment]
Reading the text surrounding the example as well as the other examples, they are intended to use Cucumber expressions, and not regular expressions. 
I do understand the text around the example could be a bit confusing as it mentions regex just before the example and then goes on to explain how `int` is a built in type that translates to `\d+`. 
Perhaps it would be better to put all text above the example, to make it easier to understand?

**Review by mlvandijk — CHANGES_REQUESTED** [review]
Example should use Cucumber expressions, not regex.
Instead of changing the example, let's rearrange the text surrounding the example (see my comment).

**Comment by mlvandijk** [comment]
@AReyes-cl Are you able to pick up the suggested changes?

**Comment by mlvandijk** [comment]
Closing this PR in favor of #430

**Pull request closed without merging**
