### PR TITLE
Xunit.Gherkin.Quick installation page link.

### PR DESCRIPTION
**Pull request by ttutisani**
[Xunit.Gherkin.Quick](https://github.com/ttutisani/Xunit.Gherkin.Quick) is a [gherkin](https://github.com/cucumber/cucumber/tree/master/gherkin) based BDD framework for .NET core.

I think this is all I had to do to add the installation link. If I missed anything, please let me know.

I renamed the existing link to specflow into "specflow" from "dotnet", since it seemed consistent with the rest of the page to have one thumbnail per framework (i.e., one for specflow and another for Xunit.Gherkin.Quick).

### CODE REVIEW

**Review by mlvandijk — CHANGES_REQUESTED** [review]
I see this PR has merge conflicts. Could you fix them please?

**Comment by ttutisani** [comment]
@mlvandijk thanks for the response! The PR is fixed and has no merge conflicts now. Please merge if no other concerns.

**Comment by mlvandijk** [comment]
LGTM, thnx

**Comment by aslakhellesoy** [comment]
Hi @ttutisani,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
