### PR TITLE
Java null pointer exception safe comparison

### PR DESCRIPTION
**Pull request by marcin-nowak-codes**

### CODE REVIEW

**Comment by mlvandijk** [comment]
Hello @marcin-nowak-codes - **Thank you very much** for wanting to contribute to the Cucumber documentation and taking the time to create a PR!
Unfortunately the suggested change does not work for multiple reasons:
1. The ternary operator in Java doesn't prevent a NPE if `today == null`.
2. The method will not compile as is due to `missing return statement` (and missing brackets)
In addition, if I recall correctly we have chosen to deliberately *not* use ternary operators in the 10 minute tutorial, as we consider an if/else statement easier to read.

So unfortunately I'm going to close your PR. 

If you would still like to help out with the documentation, we would **very much appreciate it**! Please have a look at any issues marked "Good first issues" and feel free to ask questions if there's anything you are unsure about. The best way to reach me , is on the [Cucumber Slack](https://cucumberbdd-slack-invite.herokuapp.com/). We discuss documentation in the `#docs` channel.

**Comment by aslakhellesoy** [comment]
@mlvandijk, 

It’s not the ternary operator that prevents a null pointer exception here, it’s the calling of `equals` on an object we know isn’t null (`”Friday”`).

I’ve been staring at the code to understand why it won’t compile. There is indeed a return statement, and I don’t see why brackets are needed.

The PR looks good to me

**Comment by mlvandijk** [comment]
@aslakhellesoy I copied the code into a class and got 1. compiler errors as mentioned (for example, yes there is a return statement but it is inside an if statement, meaning the method as such has no return when the condition is not met) and 2. still got an NPE.

**Comment by aslakhellesoy** [comment]
> there is a return statement but it is inside an if statement

What if statement? The if statement is deleted.

**Comment by aslakhellesoy** [comment]
@mlvandijk this is the code:

```java
static String isItFriday(String today) {
    return "Friday".equals(today) ? "TGIF" : "Nope";
}
```

I don’t see how it will fail to compile, or how it can possibly throw an NPE.

**Comment by mlvandijk** [comment]
Hmm, I don't have my original anymore so I cannot reproduce what I did. It's quite possible I made a mistake (due to jetlag). Still not sure about using ternary operator over if/else though. 
If you feel the PR should be accepted, go ahead.

**Comment by aslakhellesoy** [comment]
LGTM

**Comment by aslakhellesoy** [comment]
Can you resubmit please @marcin-nowak-codes

**Review by marcin-nowak-codes — COMMENTED** [review]
Resubmitted

**Comment by mlvandijk** [comment]
Sorry about that @marcin-nowak-codes @aslakhellesoy - I think I made a copy-paste error. I cannot reopen the issue as the branch has been deleted?

**Comment by marcin-nowak-codes** [comment]
I create another PR https://github.com/cucumber/docs.cucumber.io/pull/343

BTW Great job with Cucumber

**Comment by marcin-nowak-codes** [comment]
> 
> 
> Sorry about that @marcin-nowak-codes @aslakhellesoy - I think I made a copy-paste error. I cannot reopen the issue as the branch has been deleted?

@mlvandijk No problem. This is good that you take care so much about good documentation standards. It is very important, especially for younger developer. I wish you to have a time to keep going your work with the project!

**Comment by mlvandijk** [comment]
Thanks @marcin-nowak-codes !

**Pull request closed without merging**
