### PR TITLE
Use https links

### PR DESCRIPTION
**Pull request by aslakhellesoy**
More secure, possibly better SEO

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
This is a helpful and Web-friendly update.

**Comment by olleolleolle** [comment]
`https://www.manning.com/books/bdd-in-action` this link went to a temporary server maintenance page.

**Comment by aslakhellesoy** [comment]
Works for me:

Screenshot 2019-11-06 at 23 04 20

**Comment by olleolleolle** [comment]
It was a quite temporary situation, just enough to get netlify red.

**Pull request merged**
