### PR TITLE
Add TOC to each page

### PR DESCRIPTION
**Pull request by plaindocs**
@aslakhellesoy what do you think to formatting this and floating it right? 

This kinda overview of each page is pretty helpful

### CODE REVIEW

**Comment by olleolleolle** [comment]
I really like a long page with a table of contents.

**Comment by plaindocs** [comment]
Especially if you're unfamiliar with the domain it can really hard to know what a page is about.

**Comment by mlvandijk** [comment]
Sounds good!

**Comment by olleolleolle** [comment]
@plaindocs Will you add CSS to place this box?

**Comment by plaindocs** [comment]
I was actually hoping @aslakhellesoy would volunteer - as he has been handling the rest of the CSS. I'll discuss with him this week.

**Comment by plaindocs** [comment]
Added **basic** CSS.
Could also add a header flag to turn it on / off if necessary.

**Comment by mlvandijk** [comment]
@plaindocs Build is failing due to some dead links in blog-posts that have already been removed on master. Could you merge master into your branch or rebase onto master?

**Comment by plaindocs** [comment]
lol, looks like some more new broken links.

**Pull request merged**
