### PR TITLE
SEC: theme node packages mem, lodash.mergewith updated

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds[ **`package.json` resolutions**](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/), to avoid security warnings about issues in the Node packages for the Theme we are using.

Easy fix. Benefit: avoid warnings about security issues reported in #358

### CODE REVIEW

**Comment by mlvandijk** [comment]
@aslakhellesoy Could you have a look at this, please? I'm not familiar with these particular tools.

**Comment by mxygem** [comment]
I'm all for fixing security issues. @olleolleolle Have you tried building the site locally to see if anything breaks? Netlify doesn't build forks afaik, so that prevents me from easily checking it.

**Comment by luke-hill** [comment]
My philosophy on these kinda changes is if they pass CI and doesn't break anything merge it in. We have a revert ability.

**Comment by aslakhellesoy** [comment]
Well said @luke-hill.

@olleolleolle the `resolutions` feature is only supported by yarn (not by npm). People using npm will still see warnings.

**Comment by olleolleolle** [comment]
@aslakhellesoy I'm not aware of any equivalent to "second-order dependency hints" (my description of what `resolutions` does) for npm. Is there one?

**Comment by olleolleolle** [comment]
Ah, and about warnings displayed: this repo has `yarn.lock` (which GitHub can inspect) but no `package-lock.json`.

(I was mostly referring to the big yellow banner on the GitHub repository, about security warnings.)

**Review by mxygem — APPROVED** [review]
Thanks for helping with this. :) If things break, we can always revert.

**Pull request merged**
