### PR TITLE
Linux config

### PR DESCRIPTION
**Pull request by mdsafeeuddin**
Added a note for configuration in linux based systems

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I think cucumber-js discourages global installs. Can someone verify please?

**Comment by mattwynne** [comment]
@mdsafeeuddin can you explain what prompted you to submit this change? Did you have trouble installing and running Cucumber via your `package.json`?

**Comment by mlvandijk** [comment]
This is a follow up to #296

**Comment by mdsafeeuddin** [comment]
Hi ! 
I think I figured it out, after doing "npm install --save-dev", I'm suppose to do the "npm i" in my project directory. But at that time I was unaware about that, since I have started as a complete novice, I had to do the global installation of cucumber-js. 

If we can add this instruction of "npm i" in project directory, I hope even that could be of help.

Thanks.

**Comment by aslakhellesoy** [comment]
Global installs are discouraged. Closing this.

**Pull request closed without merging**
