### PR TITLE
Added Maven execution documentation (Fixes #315)

### LINKED ISSUE #315: Add running tests with Maven / Surefire to "things that are not Cucumber" page
We should clarify how to run tests from Maven/Surefire.
As this is not a Cucumber problem, it should go on the "Things that are not Cucumber problems" page: https://docs.cucumber.io/community/not-cucumber/

We might also want to link there from FAQ.

Source: conversation on Slack:

Bill Hoffmeier [17:34]
I am trying to run selenium cucumber-junit tests from a maven project in Bamboo. The tests run fine in an IDE, but do not run using “mvn clean test” from the command line. Command line simply builds successfully and stops. Should maven be able to run the tests?

aslak [17:51]
@Bill Hoffmeier Can you run regular unit tests from maven?
Make sure the classes end with `*Test.java`

Bill Hoffmeier [17:54]
Thanks @aslak. The classes don’t end with *Test.java. I can try and change the name. Also, as an FYI, the classes are not in src/main; they’re in src/test. Does that make a diff?
That ran the tests but I got a lot of initialization errors that I will work on resolving. Thanks!

aslak [18:03]
@Bill Hoffmeier happy to help. Your problem seems unrelated to Cucumber - it sounds more like you need to figure out how Maven’t surefire plugin works (surefire is the Maven plugin that runs JUnit tests)

### PR DESCRIPTION
**Pull request by grasshopper7**
Added Maven execution details in "Things that are not Cucumber problems" page.  File changed --community/not-cucumber.md

### CODE REVIEW

**Comment by mlvandijk** [comment]
Hi @grasshopper7 - thanks for this. It looks good. Small request: maybe we can add that the test classes should end in `*Test.java` or `*IT.java`, as that was the original question mentioned in #315. That way this PR closes everything mentioned in that issue.

**Comment by grasshopper7** [comment]
@mlvandijk  Added default name patterns in addition to the inclusion\exclusion links.

**Review by mlvandijk — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @grasshopper7,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mlvandijk** [comment]
Thanks a lot @grasshopper7

**Pull request merged**
