### PR TITLE
Typo updated from cukes to cakes

### PR DESCRIPTION
**Pull request by networkmonkey**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Nice try

**Comment by networkmonkey** [comment]
@aslakhellsoy was cukes on purpose and not meant to be cakes?

**Comment by aslakhellesoy** [comment]
Cukes is slang for cucumbers.

We've had a number of PRs without any description from brand new GitHub accounts lately, so I assumed this was a bot or hacker. Apologies if I was wrong.

**Comment by networkmonkey** [comment]
Sorry I totally missed the slang word, I was showing someone the examples and thought it was a typo 🤦‍♂️

**Comment by aslakhellesoy** [comment]
I can totally see how your suggestion makes sense if you don’t know the slang word though :-)

**Pull request closed without merging**
