### PR TITLE
Add gocuke implementation to Installation page

### LINKED ISSUE #830: New unofficial golang implementation
Not sure where to post this, but thought I should mention that we are maintaining our own golang cucumber runner: https://github.com/regen-network/gocuke. It would be good to add it to the list of unofficial libraries.

It is based off the official go gherkin and messages libraries and we intend to keep it up to date with these and also support as many of the official cucumber features as we can. Compared to godog (at least for our use cases) it has a more ergonomic integration with go `*test.T`, easier ways to pass stuff between test steps, parallel tests, and some other features we find useful.

### PR DESCRIPTION
**Pull request by aaronc**
### 🤔 What's changed?

Adds [gocuke](https://github.com/regen-network/gocuke) as a semi-official golang implementation on the Installation page.

Closes #830 

### ⚡️ What's your motivation? 

I would like to make sure that other users can find gocuke as they might find it easier to work with than the other golang implementations.

I am proposing that it be listed as "semi-official" because it uses the official github.com/cucumber/gherkin/go and github.com/cucumber/messages/go libraries under the hood and attempts to stay up to date with these dependencies.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Review by luke-hill — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @aaronc,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
Hey @aaronc this looks very interesting. Am I right that with gocuke, all features and scenarios run inside of a single test?

In other words, does this run *all* features and scenarios?

```go
gocuke.NewRunner(t, &suite{}).Run()
```

I've been wondering lately if this could be an alternative way to run Cucumber.js as well. In the JavaScript ecosystem there are so many different test runners (mocha, jest, vitest etc etc), and being able to run Cucumber within any testing tool could be quite handy.

/cc @davidjgoss

**Comment by aaronc** [comment]
> Hey @aaronc this looks very interesting. Am I right that with gocuke, all features and scenarios run inside of a single test?
> 
> In other words, does this run _all_ features and scenarios?
> 
> ```go
> gocuke.NewRunner(t, &suite{}).Run()
> ``` 

Thanks for your interest @aslakhellesoy ! So the above line will run all features and scenarios in the default path `features/*.feature`. In practice though, we find it better to have one test file per feature file and use the `Path()` option, as you can see in these examples: https://github.com/regen-network/regen-ledger/tree/main/x/ecocredit/base/keeper (such as https://github.com/regen-network/regen-ledger/blob/main/x/ecocredit/base/keeper/msg_add_class_creator_test.go#L22)

In go, tests can have sub-tests, so even though you can start with one top-level test for all features, each feature file and pickle gets run in a sub-test.

**Comment by davidjgoss** [comment]
@aslakhellesoy I think about this often...unfortunately none of the JavaScript test runners have extension points for dynamically defining and running tests in the way that, say, JUnit does.

**Pull request merged**
