### PR TITLE
added remark about eventually missing double-quote

### PR DESCRIPTION
**Pull request by frank-at-work**
Tried out the tutorial an run into the mentioned error. Adding the double-quotation marks solved the issue.

### CODE REVIEW

**Review by mlvandijk — CHANGES_REQUESTED** [review]
Thanks for pointing that out. Would you mind updating the examples to use double quotes around parameters?

**Comment by frank-at-work** [comment]
Hi @mlvandijk, I have committed the double quoted example and removed the remark block again.

I feel uncertain about the string {{% version "cucumberarchetype" %}}. What happens to it, if you copy and paste the example?

**Review by luke-hill — APPROVED** [review]
As this is just a doc piece, I'll merge this in. If people have a better solution down the line it can be improved upon

**Comment by aslakhellesoy** [comment]
Hi @frank-at-work,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
