### PR TITLE
Fix typos & inconsistencies

### PR DESCRIPTION
**Pull request by mlvandijk**
### 🤔 What's changed?

Replace {{text}} with {{block}} in several places (where relevant)
Replace "method or function" with shortcode
Remove unnecessary new lines
Add "Annotated method style" to relevant Java/Kotlin code blocks.
Move {{ /block }} to after Ruby code examples for 2 blocks.
Adding some {{block}}s for "java,kotlin,scala" as needed.
Add white line between start of {{block}} and code block (unless there was text before the code block)
Fix typos
Remove redundant semicolons and {} in Kotlin examples.
Use shortcodes for stepdef-body and expression-parameter
Fix shortcode syntax where needed.

### ⚡️ What's your motivation? 

Consistency and looking to fix shortcodes

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Comment by mpkorstanje** [comment]
@mlvandijk before you merge this, make sure the short codes don't add extra whitespace, the changes you are making now may work differently once that is fixed.

**Comment by mlvandijk** [comment]
@mpkorstanje the `{{% expression-parameter %}}` does seem to add an extra whitespace, but imho that is still better than multiple new lines when using multiple {{text}} blocks for the different languages. I don;t think I'll be able to fix all the issues in this PR, but it should fix a large portion (incl. returning the missing sections of docs). I can create a follow up issue for the remaining problems for someone else to look at.

**Comment by mpkorstanje** [comment]
It's better, but you're fixing symptoms. It's the short code magic that got broken. You've gotta figure out how the magic used to work and how it works now.

**Comment by mlvandijk** [comment]
Yes, I'm fixing symptoms at least so the text will be shown again. And then I can figure out the magic.

**Pull request merged**
