### PR TITLE
WIP: Adding anchor markings to heading

### PR DESCRIPTION
**Pull request by TomerPacific**
As suggested by the discourse, I have added the ability to add code to add anchor markings to heading. As stated in the issue, I have not been able to run a local development environment.

References issue #123

### CODE REVIEW

**Comment by plaindocs** [comment]
Thanks @TomerPacific !

You can see the site build from your changes here: https://deploy-preview-258--cucumber.netlify.com/ 

As far as I can tell, your changes are not getting picked up at all. 

I suspect you might need to tweak the syntax of the content

```
    {{- with .Content -}}
    <div>
      {{ . | replaceRE "(<h[1-9] id=\"([^\"]+)\".+)(</h[1-9]+>)" `${1}<a href="#${2}" class="hanchor" ariaLabel="Anchor"> 🔗&#xFE0E;</a> ${3}` | safeHTML }}
    </div>
    {{- end -}}
```

maybe? https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/14

**Comment by TomerPacific** [comment]
@plaindocs ,
does it look better now?

**Comment by plaindocs** [comment]
Hey @TomerPacific 

Your changes are now visible in the preview. https://deploy-preview-258--cucumber.netlify.com/

You can check that after each commit you push to the PR. As you can see, the CSS is off now. Take a look at the display and classes on master, and adjust your branch till it looks similar.

:+1:

**Comment by TomerPacific** [comment]
@plaindocs ,
I tried looking at https://cucumber.netlify.com/ and the link you posted above and I don't see a difference.
I also don't understand what you meant by the CSS being off.

**Comment by plaindocs** [comment]
Hey @TomerPacific, if we look at a page with subheadings, like this one from your preview:

https://deploy-preview-258--cucumber.netlify.com/cucumber/cucumber-expressions/

image

which corresponds to http://docs.cucumber.io/cucumber/cucumber-expressions/ on the main site

image

So you're adding the  🔗︎ symbol with the anchor link, which is great. But the formatting of the "Introduction" heading is no longer correct.

**Comment by TomerPacific** [comment]
@plaindocs ,
I see what you mean. I'll work on it and update.

**Comment by TomerPacific** [comment]
@plaindocs ,
managed to sort the issue where the h1 tags didn't close properly. Thing is, I do not understand why the CSS isn't applied to the headings.

**Comment by TomerPacific** [comment]
@plaindocs , @mlvandijk 
any help?

**Comment by plaindocs** [comment]
I *think* your `<div>` aren't quite right within the loop. 

Under the title, there is an empty content `<div>` which should contain the whole page body. 

At a guess, removing lines 13-15 of single content might fix it?

**Comment by TomerPacific** [comment]
@plaindocs ,
what you suggested fixed the issue. Let me know if it is alright that the anchor link is showing underneath the headings

**Comment by plaindocs** [comment]
Hey @TomerPacific  - looks like we're almost there!

- [x] Yeah, can you fix the line break please.

@mlvandijk anything else you can think of before we merge this?

**Comment by TomerPacific** [comment]
@plaindocs ,
regarding the formatting, I think it has to do with the CSS, since when I inspect the page I see the following : 

`h1 {
    display: block;
    font-size: 2em;
    margin-block-start: 0.67em;
    margin-block-end: 0.67em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
}`

And this is brought from the user agent.

I looked over the CSS files and found no relevant rules.

**Comment by plaindocs** [comment]
Doesn't look like the link symbol is inside the heading at all. 

```
<h1 id="keywords">Keywords </h1><a href="#keywords" class="hanchor" ariaLabel="Anchor"> 🔗&#xFE0E;</a>
```

While we're there, do we know what the `ariaLabel` stuff is?

**Comment by TomerPacific** [comment]
@plaindocs ,
the anchor link is now inside the header tag (and it has received its styling as well).

cucumber

The [ariaLabel ](https://www.w3.org/TR/WCAG20-TECHS/ARIA6.html)is an attribute to help screen readers for visitors of the web site who are vision impaired. 

Let me know if you want to keep it or remove it.

**Comment by plaindocs** [comment]
Awesome.

Should it not be `aria-label` ?

**Comment by TomerPacific** [comment]
@plaindocs,
changed aria-label attribute.

**Comment by plaindocs** [comment]
:tada: thanks a lot for your help on this @TomerPacific

**Comment by TomerPacific** [comment]
@plaindocs ,
thank you for your patience and guidance. :pray:

**Pull request merged**
