### PR TITLE
Fix a compilation error in the Selenium example

### PR DESCRIPTION
**Pull request by Flaburgan**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Hi @Flaburgan,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by plaindocs** [comment]
Thanks!

**Comment by Flaburgan** [comment]
Hi @aslakhellesoy, thank you for this warm welcome and the trust you put in new contributors.
I'm used to Cucumber because we use it in the https://github.com/diaspora/diaspora project. At work we use Java, so I'm now discovering the cucumber-jvm project. If I find other mistakes / things that can be improved in the doc, I'll open new pull requests.

**Comment by mlvandijk** [comment]
@Flaburgan Nice catch, thanks for your help! Please feel free to check the other docs / java examples and suggest improvements. Much appreciated!

**Pull request merged**
