### PR TITLE
Java Tools: fix system property name for maven

### PR DESCRIPTION
**Pull request by alb-i986**

### CODE REVIEW

**Comment by olleolleolle** [comment]
This uses the convention of lowercase with dots instead of camelcase. Looks good!

**Comment by alb-i986** [comment]
I forgot to mention:

https://github.com/cucumber/cucumber-jvm/blob/d14c437294be61bd5c43c72d16d0876b06ec6f96/core/src/main/java/io/cucumber/core/options/Constants.java#L134

**Comment by alb-i986** [comment]
I see now that actually `-Dcucumber.options` was removed recently in #1958.
For now this change is safe, but we need to remember to update the docs again as soon the #1958 is released.

**Comment by olleolleolle** [comment]
Thanks for linking to the commit - and for the vigilance about the next version.

**Pull request merged**
