### PR TITLE
Add link to pretty HTML reporting Cucumber plugin

### PR DESCRIPTION
**Pull request by jamietanna**

### CODE REVIEW

**Review by mlvandijk — COMMENTED** [review]
Thanks for the addition!
For consideration: Is this a plugin or a reporter? If plugin, maybe it would be better to add to [tools page](https://cucumber.io/docs/tools/related-tools/)?

**Comment by jamietanna** [comment]
Hey, that's a good question - I'd say its technically both? It's a Cucumber plugin that does reporting. Do you think it should sit in one or the other? Or maybe in both?

**Review by mlvandijk — APPROVED** [review]
Let's keep it under third-party reporting plugins.

**Comment by aslakhellesoy** [comment]
Hi @jamietanna,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
