### PR TITLE
add title attr on each language tab link

### PR DESCRIPTION
**Pull request by davidjgoss**

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Rookie question: I do not know that `{{ . }}` syntax. What is it?

**Comment by luke-hill** [comment]
Local level of nesting inside either go or a lot of other templating languages. So it would be equivalent in these diffs to `.Page.Params.polyglot` value during each enumeration. So probably equal to js / java / ruby / kotlin

**Comment by aurelien-reeves** [comment]
> 
> 
> Local level of nesting inside either go or a lot of other templating languages. So it would be equivalent in these diffs to `.Page.Params.polyglot` value during each enumeration. So probably equal to js / java / ruby / kotlin

Thank you.
I understood well what it does, but not from where it comes from.

**Comment by aurelien-reeves** [comment]
@davidjgoss is this still a draft?

**Comment by davidjgoss** [comment]
@aurelien-reeves it improves things although still not perfect - but yeah can be merged

**Review by aurelien-reeves — APPROVED** [review]

**Pull request merged**
