### PR TITLE
Add Gherkin formatter/validator to the list

### PR DESCRIPTION
**Pull request by glibas**

### CODE REVIEW

**Review by luke-hill — COMMENTED** [review]
The example given on that website looks a bit wrong and incorrect. Seems a bit odd to be recommending a site to check linting e.t.c. with an example that is non-comformant?

**Comment by glibas** [comment]
Hi @luke-hill , 

Fair point, thank you. Example fixed. Originally the idea was to have some errors to highlight linting and formatting functionality. So that users can try out hotkeys straight away.

**Comment by glibas** [comment]
Hi @luke-hill could you please take a look one more time

**Comment by luke-hill** [comment]
Some of it is still a bit iffy, but for now it seems ok. I'll merge this in.

**Pull request merged**
