### PR TITLE
Explain the User Story more

### PR DESCRIPTION
**Pull request by mirogta**
- Add a "Good User Story" definition + example
- Add Acceptance Criteria explanation + example

### 🤔 What's changed?

User Story definition with examples.

### ⚡️ What's your motivation? 

- I want to point other people to these Cucumber docs, but this page was almost empty.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Review by mlvandijk — CHANGES_REQUESTED** [review]
Hi @mirogta - thank you so much for stopping by and making this wonderful change. I absolutely love it! <3

I have just one small request; could you please mark all of the Gherkin scenarios as such, instead of using the formatting you currently have, to make sure formatting is consistent with the rest of the docs. And please also make sure to include the entire scenario (including the title "Scenario x"). 
You can do so by adding ```gherkin at the start and adding three closing backticks at the end. For examples, see: https://raw.githubusercontent.com/cucumber/docs/main/content/docs/gherkin/reference.md

**Comment by mirogta** [comment]
@mlvandijk - updated the formatting, please have a look again

**Review by mlvandijk — APPROVED** [review]

**Comment by mlvandijk** [comment]
Perfect @mirogta - Thank you so much for your contribution!

**Comment by aslakhellesoy** [comment]
Hi @mirogta,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
