### PR TITLE
Fix broken ordering for the Gradle steps

### PR DESCRIPTION
**Pull request by streetturtle**

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Other then whitespace I can't see any changes.

**Comment by streetturtle** [comment]
Ordered list in markdown brakes and starts from 1 if text in paragraph starts from the beginning of the line. Indenting the content allows numbering continues. Here is similar question from SO: https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list

**Comment by mlvandijk** [comment]
Thanks, that was driving me mad.

**Comment by mlvandijk** [comment]
Hop into the #docs channel on Slack if you're up for helping out some more @streetturtle !

**Pull request merged**
