### PR TITLE
Related Tools: Adds Cukedoctor

### PR DESCRIPTION
**Pull request by rmpestano**

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
I even agree with the wording - very readable!

**Comment by aslakhellesoy** [comment]
Hi @rmpestano,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mlvandijk** [comment]
Thanks @rmpestano - Please let us know if you'd like to contribute more to the documentation. The CukeDoktor documentations looked really nice!

**Comment by rmpestano** [comment]
Hi @mlvandijk, It would be really great to contribute to cucumber docs, a tool I have so much love, but I'm with a quite big 'opensource' backlog and have no time left for so much fun ;)

Thank you for the invitation and for being so kind and receptive. I promisse to come back to offer help on a near future.

**Pull request merged**
