### PR TITLE
Update related-tools.md

### PR DESCRIPTION
**Pull request by rodrigoodhin**
I would like to share with the community my library, Gocure, written in GO, but which can also help users of other languages, because I have also built a docker with an API and with a Frontend to help anyone to embed files for cucumber reports or to generate beautiful HTML reports.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Hi @rodrigoodhin 

Thanks for your contribution!

I would say I am ok with it.
Just waiting a little bit to make sure there is no objection from someone else 🙂

**Comment by rodrigoodhin** [comment]
Thanks!!! @aurelien-reeves

**Review by mlvandijk — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @rodrigoodhin,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by rodrigoodhin** [comment]
Thanks @mlvandijk and @aslakhellesoy !
It's a pleasure to make part of this community.

**Pull request merged**
