### PR TITLE
Update Docs for gherkin i-18 table

### PR DESCRIPTION
**Pull request by sohamghoshjobprofiles**
Updating docs to reflect the correct **_Hindi_** word in the _i-18 table_ for _'Rules'_
Once the code for [issue #1595 on the common repo](https://github.com/cucumber/common/issues/1595) is done, the docs will have to change. 

This Update will solve issue #630  raised to update docs

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
@sohamghoshjobprofiles thanks for your submission 👍 

We have to update [cucumber gherkin](https://github.com/cucumber/common/tree/main/gherkin) accordingly.
I see you already submit an issue for that. Would you try to submit a PR? Would you need some help to do so?

Updating translations in gherkin is explained here: https://github.com/cucumber/common/blob/main/gherkin/CONTRIBUTING.md#adding-or-updating-an-i18n-language

If you need more help, feel free to ask!

**Comment by sohamghoshjobprofiles** [comment]
@aurelien-reeves thanks for your comment. 
I would absolutely love to create a PR for the gherkin codebase too. Could you point me to the file where the change should be made? I am not very familiar with it, so it might take a couple of reviews. But it seems like the update should be trivial. Correct me if I'm wrong.

**Comment by aurelien-reeves** [comment]
You may have missed the last update to my comment :p

It is explained here: https://github.com/cucumber/common/blob/main/gherkin/CONTRIBUTING.md#adding-or-updating-an-i18n-language

You'll need to checkout the code as there is a script to execute to propagate the changes.

Update the following file: https://github.com/cucumber/common/blob/main/gherkin/gherkin-languages.json

Then execute the following from the gherkin directory (you'll need make, jq and diff command line tools to be installed):

```shell
source ../scripts/functions.sh
rsync_files
make clean
make
```

If you are not able to execute those commands, this won't be an issue. Update gherkin-languages.json and submit the PR, then specify in the description that you are not able to execute the synchronization commands. We will be able to take care of that.

Last but not least, add an entry in `gherkin/CHANGELOG.md` too as part of your PR ;)

**Comment by aurelien-reeves** [comment]
The update of this PR have already been ported to main. Closing.

However, thanks @sohamghoshjobprofiles for your contribution!

**Pull request closed without merging**
