### PR TITLE
Update reference.md

### PR DESCRIPTION
**Pull request by hosseinRezaei188**
only have a single When step per Scenario!

### 🤔 What's changed?

this is only have a single When step per Scenario, but in document It has been stated we can use `And` or `But` when we have successive `When` step.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Comment by luke-hill** [comment]
I'd rather alter the example to have multiple whens

**Review by mlvandijk — APPROVED** [review]

**Comment by luke-hill** [comment]
Hi @hosseinRezaei188 are you able to amend the examples present to include multiple `When` statements?

**Comment by hosseinRezaei188** [comment]
my issues is about can not have successive `When` in one senario.
in this [line ](https://github.com/cucumber/docs/blob/main/content/docs/gherkin/reference.md?plain=1#L212)said `It's strongly recommended you only have a single `When` step per Scenario`
but this [line](https://github.com/cucumber/docs/blob/main/content/docs/gherkin/reference.md?plain=1#L251) concept is to have multi `when` step

**Comment by luke-hill** [comment]
The one mentioning to only have 1 When step I am not sure where that came from. Looking at the git blame it was 6 years ago (Which is about when we first made the docs website). So you can consider it a leakage from the previous situation/s

**Comment by hosseinRezaei188** [comment]
> The one mentioning to only have 1 When step I am not sure where that came from. Looking at the git blame it was 6 years ago (Which is about when we first made the docs website). So you can consider it a leakage from the previous situation/s

So can use multiple when in one scenario? How? In scenario define one action for unit test not for integration test.

**Comment by luke-hill** [comment]
```
Given I am on the homepage
When I navigate to the admin panel
And I login using invalid credentials
Then I am not permitted to use the admin service
```

```
Given I am on the homepage
When I navigate to the admin panel
And I login using valid credentials
And I navigate to the metrics board
Then I can see who logged in at what time
```

**Comment by hosseinRezaei188** [comment]
in this example you say one **When** with multiple **And**.
my mind is you say in this [line](https://github.com/cucumber/docs/blob/main/content/docs/gherkin/reference.md?plain=1#L251) we can have sequential **When** steps!

**Comment by luke-hill** [comment]
Hi @hosseinRezaei188 not sure if you're still wanting to fix this up or not.

**Comment by aslakhellesoy** [comment]
Hi @hosseinRezaei188,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
