### PR TITLE
API: Add parameter list to the example showing Java's "after" hook in the annotated method style

### PR DESCRIPTION
**Pull request by XandrMaster**
Small mistake I guess

### CODE REVIEW

**Comment by olleolleolle** [comment]
I edited the title of this example-improving PR, and am asking @mlvandijk to peek at it, as I don't know the Cucumber Java API very well.

**Comment by olleolleolle** [comment]
@mlvandijk Staring at this, I wondered, "what's `self` in the block given to `Before` in the Ruby example? And, what is `this` in the JS example? Do either have any block params/function args?

**Review by mlvandijk — APPROVED** [review]
The Java change is fine (it's consistent with the previous example). Note that the parameter is optional (as stated below the example).

**Comment by aslakhellesoy** [comment]
Hi @XandrMaster,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mlvandijk** [comment]
@olleolleolle I'm not sure what you mean. Also, I'm not familiar with either the JavaScript or Ruby API, so you might need to ask someone else ;)

**Pull request merged**
