### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by marnen**
"Parenthesis" is singular; the plural is "parentheses" (just like crisis/crises); see https://www.merriam-webster.com/dictionary/parenthesis.

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
This makes the text correct, and more readable for native speakers and everyone else!

**Review by mlvandijk — APPROVED** [review]

**Comment by mlvandijk** [comment]
Fyi: build failed on a link to O"Reilly's website (http://en.oreilly.com/oscon2009/public/schedule/detail/8073); O'Reilly's site states "Due to the fires and power outages in California, oreilly.com is unavailable."

**Comment by mlvandijk** [comment]
I'll merge this anyway, and see if I can temporarily remove that link.

**Comment by mlvandijk** [comment]
Thanks for this @marnen

**Pull request merged**
