### PR TITLE
Replace "scenario" occurence by "example" in the example paragraph

### PR DESCRIPTION
**Pull request by armandabric**
The example paragraph still have some reference to the scenario

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
This consistency makes the text easier to read.

**Comment by olleolleolle** [comment]
@Spy-Seth There were a few more "scenario" in the next section, would you like to tackle them in this PR?

**Comment by armandabric** [comment]
@olleolleolle If you are referring to the "scenario" in the "Steps" section they look legit for me

If they have to be changed it will be to precise that it also apply to example: 

> Cucumber executes each step in a scenario *(or example)* one at a time

But i'm afraid it will make the text hard to read

**Comment by olleolleolle** [comment]
Alright, it's already an improvement, I think - @mlvandijk do you have readability input before I merge this?

**Review by mlvandijk — APPROVED** [review]

**Comment by mlvandijk** [comment]
LGTM. Thanks @Spy-Seth & @olleolleolle!

**Comment by aslakhellesoy** [comment]
Hi @Spy-Seth,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
